import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export type FleetReportRow = {
  machineName: string
  location: string
  lastTestDate: string
  daysSinceTest: number | null
  statusLevel: 'critical' | 'warning' | 'normal' | 'unknown'
  statusText: string
  healthScore: number | null
  nextAction: string
}

export type FleetReportMeta = {
  companyName: string
  customerEmail: string
  generatedBy: string
  generatedAt: Date
  criticalCount: number
  warningCount: number
  healthyCount: number
  avgHealthScore: number | null
}

const formatDateTime = (date: Date) => {
  return new Intl.DateTimeFormat('id-ID', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date)
}

const formatDate = (value?: string) => {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '-'

  return new Intl.DateTimeFormat('id-ID', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(date)
}

export function exportFleetReportPdf(meta: FleetReportMeta, rows: FleetReportRow[]) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header strip
  doc.setFillColor(190, 24, 93)
  doc.rect(0, 0, pageWidth, 78, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('OilTrack Fleet Condition Report', 40, 40)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Generated: ${formatDateTime(meta.generatedAt)}`, 40, 58)

  // Company block
  doc.setTextColor(17, 24, 39)
  doc.setFillColor(249, 250, 251)
  doc.roundedRect(40, 95, pageWidth - 80, 72, 8, 8, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text(meta.companyName || '-', 52, 118)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Customer Email: ${meta.customerEmail || '-'}`, 52, 136)
  doc.text(`Generated By: ${meta.generatedBy || '-'}`, 52, 151)

  // Summary cards
  const cardY = 190
  const cardGap = 12
  const cardWidth = (pageWidth - 80 - cardGap * 3) / 4
  const stats = [
    { label: 'Critical', value: String(meta.criticalCount), color: [220, 38, 38] as [number, number, number] },
    { label: 'Warning', value: String(meta.warningCount), color: [245, 158, 11] as [number, number, number] },
    { label: 'Healthy', value: String(meta.healthyCount), color: [22, 163, 74] as [number, number, number] },
    { label: 'Avg Health', value: meta.avgHealthScore !== null ? `${meta.avgHealthScore}/100` : '-', color: [30, 64, 175] as [number, number, number] },
  ]

  stats.forEach((stat, index) => {
    const x = 40 + index * (cardWidth + cardGap)

    doc.setFillColor(255, 255, 255)
    doc.setDrawColor(229, 231, 235)
    doc.roundedRect(x, cardY, cardWidth, 74, 8, 8, 'FD')

    doc.setTextColor(107, 114, 128)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text(stat.label.toUpperCase(), x + 12, cardY + 22)

    doc.setTextColor(...stat.color)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.text(stat.value, x + 12, cardY + 50)
  })

  doc.setTextColor(17, 24, 39)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Maintenance Priority Queue', 40, 292)

  autoTable(doc, {
    startY: 305,
    head: [['#', 'Machine', 'Location', 'Last Test', 'Status', 'Health', 'Next Action']],
    body: rows.map((row, index) => [
      String(index + 1),
      row.machineName,
      row.location || '-',
      `${formatDate(row.lastTestDate)}${row.daysSinceTest !== null ? ` (${row.daysSinceTest}d)` : ''}`,
      row.statusText,
      row.healthScore !== null ? `${row.healthScore}/100` : '-',
      row.nextAction,
    ]),
    headStyles: {
      fillColor: [31, 41, 55],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'left',
    },
    styles: {
      fontSize: 9,
      lineColor: [229, 231, 235],
      lineWidth: 0.4,
      cellPadding: 6,
      valign: 'top',
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    columnStyles: {
      0: { cellWidth: 26, halign: 'center' },
      1: { cellWidth: 95 },
      2: { cellWidth: 80 },
      3: { cellWidth: 90 },
      4: { cellWidth: 62 },
      5: { cellWidth: 52, halign: 'center' },
      6: { cellWidth: 130 },
    },
    didParseCell: (data) => {
      if (data.section !== 'body' || data.column.index !== 4) return

      const status = String(data.cell.raw || '').toLowerCase()
      if (status.includes('critical')) {
        data.cell.styles.textColor = [185, 28, 28]
        data.cell.styles.fontStyle = 'bold'
      } else if (status.includes('warning')) {
        data.cell.styles.textColor = [180, 83, 9]
        data.cell.styles.fontStyle = 'bold'
      } else if (status.includes('normal')) {
        data.cell.styles.textColor = [21, 128, 61]
        data.cell.styles.fontStyle = 'bold'
      }
    },
    margin: { left: 40, right: 40 },
  })

  const totalPages = doc.getNumberOfPages()
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(107, 114, 128)
    doc.text('OilTrack Confidential Report', 40, 820)
    doc.text(`Page ${page} of ${totalPages}`, pageWidth - 92, 820)
  }

  const safeCompany = (meta.companyName || 'Customer').replace(/[^a-z0-9]+/gi, '_')
  const filename = `Fleet_Report_${safeCompany}_${meta.generatedAt.toISOString().slice(0, 10)}.pdf`

  doc.save(filename)
}
