import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export type FleetReportRow = {
  machineName: string
  location: string
  lastTestDate: string
  daysSinceTest: number | null
  statusLevel: 'critical' | 'warning' | 'normal' | 'unknown'
  statusText: string
  healthScore: number | null
  nextAction: string
}

export type FleetReportMeta = {
  companyName: string
  customerEmail: string
  generatedBy: string
  generatedAt: Date
  criticalCount: number
  warningCount: number
  healthyCount: number
  avgHealthScore: number | null
}

type ReportLanguage = 'id' | 'en'

const pdfCopy = {
  id: {
    title: 'Laporan Kondisi Fleet OilTrack',
    generated: 'Dibuat pada',
    customerEmail: 'Email Customer',
    generatedBy: 'Dibuat oleh',
    maintenanceQueue: 'Antrian Prioritas Maintenance',
    page: 'Halaman',
    confidential: 'Laporan Rahasia OilTrack',
    stats: {
      critical: 'Kritis',
      warning: 'Waspada',
      healthy: 'Sehat',
      avgHealth: 'Rata-rata Kesehatan',
    },
    table: {
      machine: 'Mesin',
      location: 'Lokasi',
      lastTest: 'Tes Terakhir',
      status: 'Status',
      health: 'Kesehatan',
      nextAction: 'Tindakan Berikutnya',
    },
  },
  en: {
    title: 'OilTrack Fleet Condition Report',
    generated: 'Generated',
    customerEmail: 'Customer Email',
    generatedBy: 'Generated By',
    maintenanceQueue: 'Maintenance Priority Queue',
    page: 'Page',
    confidential: 'OilTrack Confidential Report',
    stats: {
      critical: 'Critical',
      warning: 'Warning',
      healthy: 'Healthy',
      avgHealth: 'Avg Health',
    },
    table: {
      machine: 'Machine',
      location: 'Location',
      lastTest: 'Last Test',
      status: 'Status',
      health: 'Health',
      nextAction: 'Next Action',
    },
  },
} as const

const formatDateTime = (date: Date) => {
  return new Intl.DateTimeFormat('id-ID', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date)
}

const formatDate = (value?: string) => {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '-'

  return new Intl.DateTimeFormat('id-ID', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(date)
}

const loadImageDataUrl = async (path: string) => {
  try {
    const response = await fetch(path)
    if (!response.ok) return null

    const blob = await response.blob()

    return await new Promise<string | null>((resolve) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(typeof reader.result === 'string' ? reader.result : null)
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

const loadImageDimensions = async (dataUrl: string) => {
  return await new Promise<{ width: number; height: number } | null>((resolve) => {
    const image = new Image()
    image.onload = () => resolve({ width: image.naturalWidth || image.width, height: image.naturalHeight || image.height })
    image.onerror = () => resolve(null)
    image.src = dataUrl
  })
}

const addImageContain = async (
  doc: jsPDF,
  dataUrl: string | null,
  x: number,
  y: number,
  maxWidth: number,
  maxHeight: number,
  format: 'PNG' | 'JPEG' = 'PNG'
) => {
  if (!dataUrl) return

  const dimensions = await loadImageDimensions(dataUrl)
  if (!dimensions || !dimensions.width || !dimensions.height) return

  const scale = Math.min(maxWidth / dimensions.width, maxHeight / dimensions.height)
  const width = dimensions.width * scale
  const height = dimensions.height * scale
  const offsetX = x + (maxWidth - width) / 2
  const offsetY = y + (maxHeight - height) / 2

  doc.addImage(dataUrl, format, offsetX, offsetY, width, height)
}

export async function exportFleetReportPdf(meta: FleetReportMeta, rows: FleetReportRow[], language: ReportLanguage = 'en') {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const copy = pdfCopy[language]
  const [headerImage, footerImage] = await Promise.all([
    loadImageDataUrl('/header.png'),
    loadImageDataUrl('/footer.png'),
  ])

  // --- HEADER SECTION PLACEHOLDER ---
  // (We now draw the header dynamically on all pages in the final page loop to prevent duplicates)

  // --- CUSTOMER PROFILE CARD ---
  const profileY = headerImage ? 85 : 100
  doc.setTextColor(17, 24, 39)
  doc.setFillColor(248, 250, 252)
  doc.setDrawColor(226, 232, 240)
  doc.roundedRect(40, profileY, pageWidth - 80, 72, 10, 10, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text(meta.companyName || '-', 55, profileY + 25)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text(`${copy.customerEmail}: ${meta.customerEmail || '-'}`, 55, profileY + 45)
  doc.text(`${copy.generatedBy}: ${meta.generatedBy || '-'}`, 55, profileY + 60)

  // --- SUMMARY STATS CARDS ---
  const cardY = profileY + 88
  const cardGap = 12
  const cardWidth = (pageWidth - 80 - cardGap * 3) / 4
  const stats = [
    { label: copy.stats.critical, value: String(meta.criticalCount), color: [220, 38, 38], bg: [254, 242, 242] },
    { label: copy.stats.warning, value: String(meta.warningCount), color: [217, 119, 6], bg: [255, 251, 235] },
    { label: copy.stats.healthy, value: String(meta.healthyCount), color: [21, 128, 61], bg: [240, 253, 244] },
    { label: copy.stats.avgHealth, value: meta.avgHealthScore !== null ? `${meta.avgHealthScore}` : '-', color: [30, 64, 175], bg: [239, 246, 255] },
  ]

  stats.forEach((stat, index) => {
    const x = 40 + index * (cardWidth + cardGap)

    // Shadow-like effect
    doc.setFillColor(241, 245, 249)
    doc.roundedRect(x + 1, cardY + 1, cardWidth, 80, 8, 8, 'F')
    
    doc.setFillColor(255, 255, 255)
    doc.setDrawColor(226, 232, 240)
    doc.roundedRect(x, cardY, cardWidth, 80, 8, 8, 'FD')

    // Top indicator line
    doc.setFillColor(stat.color[0], stat.color[1], stat.color[2])
    doc.rect(x + 10, cardY, cardWidth - 20, 3, 'F')

    doc.setTextColor(100, 116, 139)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.text(stat.label.toUpperCase(), x + 12, cardY + 22)

    doc.setTextColor(stat.color[0], stat.color[1], stat.color[2])
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.text(stat.value, x + 12, cardY + 54)
    
    if (index === 3 && meta.avgHealthScore !== null) {
      doc.setFontSize(10)
      doc.text('/100', x + 12 + doc.getTextWidth(stat.value), cardY + 54)
    }
  })

  // --- TABLE SECTION ---
  doc.setTextColor(17, 24, 39)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text(copy.maintenanceQueue, 40, cardY + 115)

  autoTable(doc, {
    startY: cardY + 130,
    head: [['#', copy.table.machine, copy.table.location, copy.table.lastTest, copy.table.status, copy.table.health, copy.table.nextAction]],
    body: rows.map((row, index) => [
      String(index + 1),
      row.machineName,
      row.location || '-',
      `${formatDate(row.lastTestDate)}${row.daysSinceTest !== null ? ` (${row.daysSinceTest}d)` : ''}`,
      row.statusText.toUpperCase(),
      row.healthScore !== null ? `${row.healthScore}` : '-',
      row.nextAction,
    ]),
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'left',
      fontSize: 10,
    },
    styles: {
      fontSize: 9,
      lineColor: [241, 245, 249],
      lineWidth: 0.5,
      cellPadding: 8,
      valign: 'middle',
    },
    columnStyles: {
      0: { cellWidth: 26, halign: 'center', textColor: [100, 116, 139] },
      1: { cellWidth: 95, fontStyle: 'bold' },
      2: { cellWidth: 80, textColor: [71, 85, 105] },
      3: { cellWidth: 95, fontSize: 8.5 },
      4: { cellWidth: 70, halign: 'center' },
      5: { cellWidth: 45, halign: 'center', fontStyle: 'bold' },
      6: { cellWidth: 104, fontSize: 8 },
    },
    alternateRowStyles: {
      fillColor: [252, 253, 254],
    },
    didParseCell: (data) => {
      if (data.section !== 'body' || data.column.index !== 4) return

      const status = String(data.cell.raw || '').toLowerCase()
      if (status.includes('critical')) {
        data.cell.styles.fillColor = [254, 242, 242]
        data.cell.styles.textColor = [185, 28, 28]
        data.cell.styles.fontStyle = 'bold'
      } else if (status.includes('warning')) {
        data.cell.styles.fillColor = [255, 251, 235]
        data.cell.styles.textColor = [180, 83, 9]
        data.cell.styles.fontStyle = 'bold'
      } else if (status.includes('normal')) {
        data.cell.styles.fillColor = [240, 253, 244]
        data.cell.styles.textColor = [21, 128, 61]
        data.cell.styles.fontStyle = 'bold'
      }
    },
    margin: { top: 90, left: 40, right: 40, bottom: 80 },
  })

  // --- HEADER & FOOTER SECTION LOOP ---
  const totalPages = doc.getNumberOfPages()
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page)
    
    // Draw Header
    if (headerImage) {
      await addImageContain(doc, headerImage, 0, 0, pageWidth, 72)
    } else {
      const gradientColors = [[190, 24, 93], [157, 23, 77]]
      doc.setFillColor(gradientColors[0][0], gradientColors[0][1], gradientColors[0][2])
      doc.rect(0, 0, pageWidth, 85, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(16)
      doc.text(copy.title, 40, 42)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(255, 255, 255, 0.8)
      doc.text(`${copy.generated}: ${formatDateTime(meta.generatedAt)}`, 40, 60)
    }

    // Draw Footer
    if (footerImage) {
      await addImageContain(doc, footerImage, 0, pageHeight - 52, pageWidth, 52)
    } else {
      doc.setDrawColor(226, 232, 240)
      doc.line(40, pageHeight - 60, pageWidth - 40, pageHeight - 60)
    }

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text(copy.confidential, 40, pageHeight - 25)
    doc.text(`${copy.page} ${page} of ${totalPages}`, pageWidth - 95, pageHeight - 25)
  }

  const safeCompany = (meta.companyName || 'Customer').replace(/[^a-z0-9]+/gi, '_')
  const filename = `Fleet_Report_${safeCompany}_${meta.generatedAt.toISOString().slice(0, 10)}.pdf`

  doc.save(filename)
}
